<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="APL-PG02H75Z" failures="1" tests="5" name="Personal Loan" time="0.094" errors="0" timestamp="2025-01-02T14:56:25 IST">
  <testcase classname="test.day2" name="ploan" time="0.014"/>
  <testcase classname="test.day1" name="demo" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.demo(day1.java:20)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="test.day4" name="LoginAPIHomeLoan" time="0.003"/>
  <testcase classname="test.day4" name="MobileLoginHomeLoan" time="0.003"/>
  <testcase classname="test.day4" name="WebLoginHomeLoan" time="0.003"/>
  <testcase classname="test.day1" name="day1Demo" time="0.0">
    <ignored/>
  </testcase> <!-- day1Demo -->
</testsuite> <!-- Personal Loan -->
